# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e702d8889733da5d004141787b68cffb3a134306023c85e2f4c4629db967f58753e70c6316cc0468dceb53cabc92f05b9bacc9682af6727e1beecb17412e3bf9

test:
  secret_key_base: a5187a69c645a36e9f23f4c23ff895d051eb3a932f37ce7f5ba28cc54c21050f5948d385f49b2759b6b6308d745c152e72e0edd0c5bda0a0dfad1c401afc3f63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
